const games = [{
  name: 'MLBB',
  full_gamename: 'Mobile Legend Bang Bang',
  description: `Mobile Legends is a popular mobile multiplayer online battle arena (MOBA) game developed by Moonton for iOS and Android. Players engage in fast-paced 5v5 matches where teams aim to destroy the enemy's base while defending their own. Matches last around 10 to 15 minutes, making it ideal for quick play. Players choose from a variety of heroes with unique abilities and roles, including tank, fighter, assassin, mage, marksman, and support. Teamwork and strategy are key to success. The game offers multiple modes, including ranked and casual play, and features a thriving esports scene with events like the Mobile Legends Professional League (MPL). Free to play, it includes in-app purchases for cosmetic items like hero skins.`,
  videogame_link: `mlbb-page.html#game-videos`,
  gamersgallery: `mlbb-page.html#game-gallery`,
  thumbnail_image: 'mlbb-thumbnail.avif',
  cover_image: 'mlbb-cover.jpg',
  short_desc: `Mobile Legends is a popular multiplayer online battle arena (MOBA) game developed and published by Moonton. It is designed specifically for mobile devices (iOS and Android) and has gained a significant player base worldwide.`,
  link: 'mlbb-page.html',
  trailer: 'mlbb-trailer.mp4',
  images: [
    {imgsrc: 'image1.png',
      imgalt: 'MLBB image 1',
    },
    {imgsrc: 'image2.png',
      imgalt: 'MLBB image 2', 
    },
    {imgsrc: 'image3.png',
      imgalt: 'MLBB image 3',
    },
    {imgsrc: 'image4.png',
      imgalt: 'MLBB image 4',
    },
    {imgsrc: 'image5.png',
      imgalt: 'MLBB image 5',
    },
    {imgsrc: 'image6.png',
      imgalt: 'MLBB image 6',
    },
    {imgsrc: 'image7.png',
      imgalt: 'MLBB image 7',
    },
    ],
  playersgallery: [
    {imgsrc: 'image1.png',
      imgalt: 'Meme 1',
      imgdesc: '',
      caption: 'Meme 1',
    },
    {imgsrc: 'image2.png',
      imgalt: 'Meme 2',
      imgdesc: '',
      caption: 'Meme 2',
    },
    {imgsrc: 'image9.png',
      imgalt: 'Collab AOT Skin',
      imgdesc: 'Moonton Collaboration with the Attack of the Titans',
      caption: 'Attack of the Titans',
    }, 
    {imgsrc: 'image3.png',
      imgalt: 'Meme 3',
      imgdesc: '',
      caption: 'Meme 3',
    }, 
    {imgsrc: 'image7.png',
      imgalt: 'Collab JJK Skin',
      imgdesc: 'Moonton Collaboration with Jujutsu Kaisen',
      caption: 'Jujutsu Kaisen',
      }, 
    {imgsrc: 'image4.png',
      imgalt: 'Meme 4',
      imgdesc: '',
      caption: 'Meme 4', 
    },
    {imgsrc: 'image5.png',
      imgalt: 'Meme 5',
      imgdesc: '',
      caption: 'Meme 5',
    },
    {imgsrc: 'image6.png',
      imgalt: 'Meme 6',
      imgdesc: '',
      caption: 'Meme 6',
    },
    {imgsrc: 'image8.png',
      imgalt: 'Collab KoF Skin',
      imgdesc: 'Moonton Collaboration with King of Fighters',
      caption: 'King of Fighters',
    },
    ],
  videogame:[
    {videosrc: 'chou-withoutme.mp4',
      videoalt: 'Chou - Without Me',
      videodesc: 'Chou freestyles with Without Me by Eminem background music ',
      videocaption: 'Chou - Without Me',
    },
    {videosrc: 'kagura-highlights.mp4',
      videoalt: 'Kagura  Highlights',
      videodesc: 'Kagura gameplay highlights and Freestyles with Without Me',
      videocaption: 'Kagura Highlights',
    },
    {videosrc: 'claude-mayhem.mp4',
      videoalt: 'Claude  Mayhem Gameplay',
      videodesc: 'Claude Mayhem gameplay highlights in Mayhem mode',
      videocaption: 'Claude Mayhem',
    },
    {videosrc: 'kaguraFire.mp4',
      videoalt: 'Kagura - Fire',
      videodesc: 'Kagura - Fire (2NE1)',
      videocaption: 'Kagura - Fire',
    },
    {videosrc: 'irithelandodette.mp4',
      videoalt: 'Irithel and Odette',
      videodesc: 'Irithel and Odette Saving each other',
      videocaption: 'Irithel and Odette',
    },
    {videosrc: 'kagurahooktutorial.mp4',
      videoalt: 'Kagura Hook Tutorial',
      videodesc: 'Kagura Hook Tutorial',
      videocaption: 'Kagura Hook Tutorial',
    },
  ],
},
{
  name: 'COC',
  full_gamename: 'Clash of Clans',
  description: `Clash of Clans is a popular mobile strategy game developed by Supercell, released in 2012. Players build and upgrade villages, manage resources like gold and elixir, and train troops for battle. The core gameplay involves attacking other players’ villages to steal resources and defending against raids. Players can join clans to share troops and participate in Clan Wars, strategic team-based battles where they earn stars by defeating enemy bases. The game is free-to-play, with in-app purchases available to speed up progress. Frequent updates and a dedicated global community have helped maintain its success in the mobile gaming world.`,
  videogame_link: `coc-page.html#game-videos`,
  gamersgallery: `coc-page.html#game-gallery`,
  thumbnail_image: `coc-thumbnail.jpg`,
  cover_image: `coc-cover.avif`,
  short_desc: `Clash of Clans is a popular mobile strategy game developed and published by Supercell. The game is set in a fantasy-themed world where players build and upgrade their own villages, train armies, and engage in battles against other players or computer-generated enemies.`,
  link: `coc-page.html#`,
  trailer: `coc-trailer.mp4`,
  images: [
    {imgsrc: 'image1.png',
      imgalt: 'COC image 1',
    },
    {imgsrc: 'image2.png',
      imgalt: 'COC image 2', 
    },
    {imgsrc: 'image3.png',
      imgalt: 'COC image 3',
    },
    {imgsrc: 'image4.png',
      imgalt: 'COC image 4',
    },
    {imgsrc: 'image5.png',
      imgalt: 'COC image 5',
    },
    {imgsrc: 'image6.png',
      imgalt: 'COC image 6',
    },
    {imgsrc: 'image7.png',
      imgalt: 'COC image 7',
    },
    ],
  playersgallery: [
    {imgsrc: 'image1.png',
      imgalt: 'Art Layout 1',
      imgdesc: 'Base Sword layout',
      caption: 'Base Layout 1',
    },
    {imgsrc: 'image2.png',
      imgalt: 'Base Layout 1',
      imgdesc: 'War Base layout',
      caption: 'War Base Layout 1',
    },
    {imgsrc: 'image3.png',
      imgalt: 'Wall Layout 1',
      imgdesc: 'Base Wall layout',
      caption: 'Base Wall Layout 1',
    }, 
    {imgsrc: 'image4.png',
      imgalt: 'Art Layout 2',
      imgdesc: 'Base Gun layout',
      caption: 'War Base Layout 2',
    }, 
    {imgsrc: 'image5.png',
      imgalt: 'builder Base Layout 1',
      imgdesc: 'Builder Base layout',
      caption: 'Builder Base',
    },
  ],
  videogame: [
    {videosrc: 'aerialattack.mp4',
      videoalt: 'Aerial Attack',
      videocaption: 'Aerial Attack ',
      videodesc: 'Aerial Attack in Clan War',
    },
    {videosrc: 'canonfunny.mp4',
      videoalt: 'Canon Funny',
      videocaption: 'Canon Funny Moment',
      videodesc: 'Canon Troop Funny Moment',
    },
    {videosrc: 'eaglealtactivate.mp4',
      videoalt: 'Eagle Alt Activate',
      videocaption: 'Eagle Altillery Activate',
      videodesc: 'Activate Eagle Altillery and your dead',
    },
    {videosrc: 'pekkafunny.mp4',
      videoalt: 'Pekka Funny',
      videocaption: 'Pekka Funny Moment',
      videodesc: 'Pekka got drunk and got hangover',
    },
  ],
},
{
  name: 'CODM',
  full_gamename: 'Call of Duty Mobile',
  description: `Call of Duty: Mobile is a free-to-play first-person shooter developed by TiMi Studios and published by Activision, released in October 2019. The game brings the iconic Call of Duty franchise to mobile, offering modes like Team Deathmatch, Domination, and Battle Royale, where up to 100 players fight to be the last one standing. It features popular maps like Nuketown and Crash, along with exclusive mobile maps. Players can customize weapons, equipment, and character skins to suit different playstyles. The game receives regular updates with new content, including weapons and limited-time events. Free-to-play, it includes in-game purchases for cosmetics and Battle Passes, providing both casual and competitive gameplay.`,
  videogame_link: `codm-page.html#game-videos`,
  gamersgallery: `codm-page.html#game-gallery`,
  thumbnail_image: `codm-thumbnail.jpg`,
  cover_image: `codm-cover.webp`,
  short_desc: `Call of Duty: Mobile is a free-to-play first-person shooter game developed by TiMi Studios and published by Activision for mobile devices. Released in October 2019, the game brings the iconic Call of Duty series to smartphones, offering a variety of modes, maps, and customization options. It is available on both iOS and Android.`,
  link: `codm-page.html#`,
  trailer: `codm-trailer.mp4`,
  images: [
    {imgsrc: 'image1.png',
      imgalt: 'CODM image 1',
    },
    {imgsrc: 'image2.png',
      imgalt: 'CODM image 2', 
    },
    {imgsrc: 'image3.png',
      imgalt: 'CODM image 3',
    },
    {imgsrc: 'image4.png',
      imgalt: 'CODM image 4',
    },
    {imgsrc: 'image5.png',
      imgalt: 'CODM image 5',
    },
    {imgsrc: 'image6.png',
      imgalt: 'CODM image 6',
    },
    {imgsrc: 'image7.png',
      imgalt: 'CODM image 7',
    },
    ],
  playersgallery: [
    {imgsrc: 'image1.png',
      imgalt: 'Call of Duty Mobile',
      imgdesc: '',
      caption: 'Call of Duty Mobile',
    },
    {imgsrc: 'image2.png',
      imgalt: 'AK-47 Radiance',
      imgdesc: 'AK-47 Radiance Legendary Skin Weapon',
      caption: 'AK-47 Radiance',
    },
    {imgsrc: 'image3.png',
      imgalt: 'AK-47 Radiance Yellow',
      imgdesc: 'AK-47 Radiance (Yellow) Legendary Skin Weapon',
      caption: 'AK-47 Radiance (Yellow)',
    }, 
    {imgsrc: 'image4.png',
      imgalt: 'Main Operator',
      imgdesc: 'Camoplauge Skinless Operator',
      caption: 'Operator',
    }, 
    {imgsrc: 'image5.png',
      imgalt: 'Ghost Oprator 1',
      imgdesc: 'Red Ghost Operator',
      caption: 'Operator',
    },
    {imgsrc: 'image6.png',
      imgalt: 'Ghost Oprator 2',
      imgdesc: 'Ghost Operators',
      caption: 'Squad Operator',
    },
  ],
  videogame: [
    {videosrc: 'ThernalSniper.mp4',
      videoalt: 'Sniper Thermal Arctic',
      videocaption: 'Using Arctic Thermal Scope',
      videodesc: 'Squad VS Arctic User',
    },
    {videosrc: 'GhostPeeking.mp4',
      videoalt: 'Ghost peek',
      videocaption: 'Ghost peeking using sniper',
      videodesc: 'Ghost peeking',
    },
    {videosrc: 'executeanimation.mp4',
      videoalt: 'Execute animation',
      videocaption: 'Execute animation compilation',
      videodesc: 'Dancing Execution ',
    },
    {videosrc: 'birdsofafeather.mp4',
      videoalt: '1v1',
      videocaption: 'Music (Birrds of Feather)',
      videodesc: '1 VS 1',
    },
    {videosrc: 'aptSniper.mp4',
      videoalt: 'Sniper APT',
      videocaption: 'Sniper highlights',
      videodesc: 'Sniper - APT',
    },
  ],
}
];

export default games;
